version: '3.9'

services:
  php:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80
    networks:
      - mysql-phpmyadmin

  # mysql
  db:
    image: mysql:8.0.40
    volumes:
      - mysqldata:/var/lib/mysql
      # - ./db_project.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"
    # restart: unless-stopped
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: db_project
    networks:
      - mysql-phpmyadmin
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 300M
      PMA_ARBITRARY: 1
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  mysqldata: